language: csharp
dist: trusty
solution: SmsCharacterCalculator.sln
mono: none
dotnet: 2.1.502

install:
  - dotnet restore

script:
- dotnet build
- dotnet test SmsCharacterCalculator.Test/SmsCharacterCalculator.Test.csproj
