name: Build & test

on:
  - push
  - pull_request

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore
      - name: test
        run: dotnet test --no-restore --no-build --verbosity normal
